export const SUPABASE_URL = 'https://exdwvsjidkpnlyzstnzl.supabase.co'

export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZHd2c2ppZGtwbmx5enN0bnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4OTI1MjksImV4cCI6MjA5OTQ2ODUyOX0.qXtWFORQREoput9pGeugb6o8KAm8fqol4ZzWPkNrBQc'

export const SUPABASE_SERVICE_ROLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZHd2c2ppZGtwbmx5enN0bnpsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4Mzg5MjUyOSwiZXhwIjoyMDk5NDY4NTI5fQ.4tw_JrLUus8RwS4k7GSN9cb2OnbcgBRNX0EVcEdtE2w'

